title: Radomir Wojtera
description: Versatile Software Engineer with 15+ years of hands-on experience crafting digital solutions
remote_theme: "godalming123/minimal"
plugins:
  - jekyll-remote-theme

include:
  - _includes/head.html
