title: Radomir Wojtera
description: Staff / Lead Frontend Engineer | React, Next.js & Developer Tooling
author: Radomir Wojtera
url: "https://www.radomir.dev"
image: /assets/images/the_face.png
twitter_username: phantombit
github_username: tiriana
remote_theme: "godalming123/minimal"
plugins:
  - jekyll-remote-theme

include:
  - _includes/head.html