title: Radomir Wojtera
description: Senior Software Engineer specializing in React and TypeScript, with full-stack capabilities
remote_theme: "godalming123/minimal"
plugins:
  - jekyll-remote-theme

include:
  - _includes/head.html
